name: probot-sentiment-bot
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '8.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
